//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Craft.Net.Data.Items
{
    
    public class BedItem : Item
    {
        public override ushort Id
        {
            get
            {
                return 355;
            }
        }

        public override void OnItemUsed(Vector3 clickedBlock, Vector3 clickedSide, Vector3 cursorPosition, World world, Entities.Entity usedBy)
        {
            var near = world.GetBlock(clickedBlock + clickedSide);
        }
    }
}
