//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Craft.Net.Data.Blocks;
using Craft.Net.Data.Entities;
namespace Craft.Net.Data.Items
{
    
    public class BucketItem : Item
    {
        public override ushort Id
        {
            get
            {
                return 325;
            }
        }

        public override void OnItemUsed(World world, Vector3 clickedBlock, Vector3 clickedSide, Vector3 cursorPosition, Entities.Entity usedBy)
        {
            PlayerEntity entity = (PlayerEntity)usedBy;
            // TODO: Check for source block
            // TODO: Survival
            if (world.GetBlock(clickedBlock + clickedSide) is WaterFlowingBlock || world.GetBlock(clickedBlock + clickedSide) is WaterStillBlock)
            {
                world.SetBlock(clickedBlock + clickedSide, new AirBlock());
            }
            if (world.GetBlock(clickedBlock + clickedSide) is LavaFlowingBlock || world.GetBlock(clickedBlock + clickedSide) is LavaStillBlock)
            {
                world.SetBlock(clickedBlock + clickedSide, new AirBlock());
            }
        }
    }
}
