//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Craft.Net.Data.Items
{
    public class EggItem : Item
    {
        public override ushort Id
        {
            get
            {
                return 344;
            }
        }

        public override byte MaximumStack
        {
            get { return 16; }
        }
    }
}