//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Craft.Net.Data.Blocks;

namespace Craft.Net.Data.Items
{

   public class RedstoneRepeaterItem : Item
   {
      public override ushort Id
      {
         get
         {
            return 356;
         }
      }

      public override void OnItemUsedOnBlock(World world, Vector3 clickedBlock, Vector3 clickedSide, Vector3 cursorPosition, Entities.Entity usedBy)
      {
         if (world.GetBlock(clickedBlock + clickedSide) == 0)
            world.SetBlock(clickedBlock + clickedSide, new RedstoneRepeaterBlock(DataUtility.DirectionByRotationFlat(usedBy)));
         }
      }
}