using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Craft.Net.Common
{
    public enum Biome
    {
        Ocean = 0,
        Plains = 1,
        Desert = 2,
        ExtremeHills = 3,
        Forest = 4,
        Taiga = 5,
        Swampland = 6,
        River = 7,
        Hell = 8,
        Sky = 9,
        FrozenOcean = 10,
        FrozenRiver = 11,
        IcePlains = 12,
        IceMountains = 13,
        MushroomIsland = 14,
        MushroomIslandShore = 15,
        Beach = 16,
        DesertHills = 17,
        ForestHills = 18,
        TaigaHills = 19,
        ExtremeHillsEdge = 20,
        Jungle = 21,
        JungleHills = 22,
        JungleEdge = 23,
        DeepOcean = 24,
        StoneBeach = 25,
        ColdBeach = 26,
        BirchForest = 27,
        BirchForestHills = 28,
        RoofedForest = 29,
        ColdTaiga = 30,
        ColdTaigaHills = 31,
        MegaTaiga = 32,
        MegaTaigaHills = 33,
        ExtremeHillsPlus = 34,
        Savanna = 35,
        SavannaPlateau = 36,
        Mesa = 37,
        MesaPlateauF = 38,
        MesaPlateau = 39,
        SunflowerPlains = 129,
        DesertM = 130,
        ExtremeHillsM = 131,
        FlowerForest = 132,
        TaigaM = 133,
        SwamplandM = 134,
        IcePlainsSpikes = 140,
        IceMountainsSpikes = 141,
        JungleM = 149,
        JungleEdgeM = 151,
        BirchForestM = 155,
        RoofedForestM = 157,
        ColdTaigaM = 158,
        MegaSpruceTaiga = 160,
        MegaSpruceTaiga2 = 161,
        ExtremeHillsPlusM = 162,
        SavannaM = 163,
        SavannaPlateauM = 164,
        MesaBryce = 165,
        MesaPlateauFM = 166,
        MesaPlateauM = 167
    }
}
